export default {
algeria: '/algeria.svg',
angola: '/angola.svg',
boc: '/Backofcard.svg',
benin: '/benin.svg',
botswana: '/botswana.svg',
"burkina faso": '/burkinafaso.svg',
cameroon: '/cameroon.svg',
"central african republic": '/car.svg',
chad: '/chad.svg',
congo: '/congo.svg',
"d.r.c.": '/drc.svg',
egypt: '/egypt.svg',
eritrea: '/eritrea.svg',
ethiopia: '/ethiopia.svg',
gabon: '/gabon.svg',
ghana: '/ghana.svg',
guinea: '/guinea.svg',
"ivory coast": '/ivorycoast.svg',
kenya: '/kenya.svg',
liberia: '/liberia.svg',
libya: '/libya.svg',
madagascar: '/madagascar.svg',
mali: '/mali.svg',
mauritania: '/mauritania.svg',
morocco: '/morocco.svg',
mozambique: '/mozambique.svg',
namibia: '/namibia.svg',
niger: '/niger.svg',
nigeria: '/nigeria.svg',
planeB: '/PlaneB.png',
planeG: '/PlaneG.png',
planeO: '/PlaneO.png',
planeP: '/PlaneP.png',
planeY: '/PlaneY.png',
rwanda: '/rwanda.svg',
senegal: '/senegal.svg',
"sierra leone": '/sierraleone.svg',
somalia: '/somalia.svg',
"south africa": '/southafrica.svg',
sudan: '/sudan.svg',
tanzania: '/tanzania.svg',
togo: '/togo.svg',
tunisia: '/tunisia.svg',
uganda: '/uganda.svg',
zambia: '/zambia.svg',
zimbabwe: '/zimbabwe.svg',
car: '/Car.png'
}

// pink, blue, green, orange, yellow